# Generated by Django 3.2.7 on 2021-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.CharField(default='administrator', max_length=255),
        ),
    ]
