# Generated by Django 3.0.6 on 2021-09-18 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_product_countn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='countn',
            new_name='count',
        ),
    ]
