# Generated by Django 3.0.6 on 2021-09-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210918_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cart_count',
            field=models.IntegerField(default=0),
        ),
    ]
